from centos

add https://lug.ustc.edu.cn/wiki/_export/code/mirrors/help/centos?codeblock=3 /etc/yum.repos.d/CentOS-Base.repo

run yum install -y epel-release
add *.repo /etc/yum.repos.d/

# If apply the cache the image would be too large...
# run yum makecache
run yum -y install iproute
